### PR TITLE
Made "Mobile Responsive" mostly...

### PR DESCRIPTION
**Pull request by FibreChips**
So, it mostly works. I added some comments in HTML/JS, and most of my stuff I added in CSS is at the bottom.

I'm free pretty much all weekend if you want to meet up and work on making it use angular, but no promises on that lol.

The only real issue that I can't work around is HTML structure, which can be easily fixed when you switch over to angular.

### CODE REVIEW

**Comment by scottfoltz** [comment]
Things got messed up when I merged your commit into my project. the
formatting looked a bit wonky for some reason. did you test it on the
desktop as well? I reverted, and Im gona look at your changes to see if I
could just add them.

Do you have a link/file with it working on mobile and desktop?

**Comment by FibreChips** [comment]
I mean you can look at it directly on my github(I think). However, if by
weird formatting you mean that the tabs/indents are off in the code, its
because I use a bigger indent in my editor than you do in yours.

If its on the website that it looks weird, I'm not super sure what you
mean. (And I see you already rolled back, so I can't check it out on my
phone)

**Comment by scottfoltz** [comment]
I'll merge again just so you can check it out.

**Comment by scottfoltz** [comment]
fuck... it doesn't look like I can merge it again. I'll just copy/paste the files from the commit over my project.

**Comment by FibreChips** [comment]
Let me know when you do.

**Comment by scottfoltz** [comment]
did you set up node and express with this too?

**Comment by FibreChips** [comment]
I did, but only because I need a local server to test on my phone like how
I showed you.

It's not necessary to run.

**Comment by FibreChips** [comment]
Also, I'm at the comedian thing now, so I won't be able to look at it until
after.

**Comment by FibreChips** [comment]
Okay, this is what I'm seeing. Yeah, it can be broken a bit, but that can
be fixed later.

I can look at it more after the show.
On Jan 22, 2016 7:55 PM, "Doug Linning" <douglinning@gmail.com> wrote:

Also, I'm at the comedian thing now, so I won't be able to look at it until
after.

**Comment by scottfoltz** [comment]
It all looks good! Next up for mobile optimization is the navbar. I'll probably end up working on that tonight. 

Also, the scroll function works! I had the same line like that before, I just wasnt calling it at the right time, i guess

**Pull request merged**
